apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/client.yaml
  - manifests/config-map.yaml
  - manifests/cronjob-curl.yaml
  - manifests/ingress.yaml
  - manifests/postgres-statefulset.yaml
  - manifests/server.yaml

images:
  - name: client-image
    newName: sirpacoder/client:v3.03
  - name: server-image
    newName: sirpacoder/server:v3.03
  - name: cronjob-image
    newName: sirpacoder/wiki_url:v3.03
