apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/client.yaml
  - manifests/config-map.yaml
  - manifests/cronjob-curl.yaml
  - manifests/ingress.yaml
  - manifests/postgres-statefulset.yaml
  - manifests/server.yaml

images:
  - name: CLIENT_IMAGE
    newName: sirpacoder/client:v3.03
  - name: SERVER_IMAGE
    newName: sirpacoder/server:v3.03
  - name: CRONJOB_IMAGE
    newName: sirpacoder/wiki_url:v3.03
