apiVersion: v1
kind: Secret
metadata:
    name: postgres-pw
    namespace: project
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:7t0+5NQka91hDn4e,iv:fdQlIlFQStLOrCV3KBK+Mo93MJSrntXakXqRYs5a/rg=,tag:amjdzAGn07UrbtUYjPO+hQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pzdfmv62zs70u0g7hhhvmlsfa6ykw0xq95ycwkfl0qd36pslfghs0pnp5w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFd0wveGN3VG0wNFNSWGNM
            bTRlTU9EQ1lhb2VGTVdQdlVhWitUSWoxZlJZCk5UNHJTVWpxQ0hEMngyeG9pREpD
            NVcyK3NncFM4UFJhRE1Nd0pkTHZtZGcKLS0tIGpJbVFJWmRkQ1NkbzRNZXdmQmdm
            Q0pwcHh4RjNkM1lzU1JWS2srQUJwSVkKgXTEGS0JBHkzGU/AxpI7jn/OBgq/7L+H
            O0bIuhZXb5OBHckK5ivL1tXyI5p/OfvwUYnOiuQ/jSkKEUftCXtWGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-12T12:37:52Z"
    mac: ENC[AES256_GCM,data:55FUyNQ3wb+/EoqbnsjlD7J9NA/X0WeYjESHJQvX1rD+hOE/U2Qtvjc3myjHnpV/t1nak5KM0aIqRsWMaW/026B30tj684qDf1+yPIgqkdBfG7C4PLjSrNUOcyPpPSyQibwXYZAgqDxFLedaHfXWqPIDKyB2MPAlpOlC0SYIqwE=,iv:GyzNi8KpB3h5SsGyO1RT5nTQSSc1jT89flje10l2Q/8=,tag:ud1uOz6sQkA7jiNct12yrg==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
