# Rollout
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: client-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  strategy:
    canary:
      steps:
      - setWeight: 25
      - pause:
          duration: 30s
      - setWeight: 50
      - pause:
          duration: 30s
      - analysis:
          templates:
          - templateName: cpu-usage-rate
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: sirpacoder/client:v4.06
          imagePullPolicy: Always
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 10
            httpGet:
              path: /healthz
              port: 3000
          resources:
            requests:
              memory: '1Gi'
              cpu: '500m'
            limits:
              memory: '10Gi'
              cpu: '500m'

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: client-svc
  namespace: project
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
