apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- /broadcaster.yaml
- /client.yaml
- /config-map.yaml
- /cronjob.yaml
- /server.yaml
- /horizontalpodautoscaler.yaml
- /ingress.yaml
- /postgres-statefulset.yaml
- /server.yaml
images:
- name: PROJECT_BROADCASTER
  newName: sirpacoder/broadcaster
  newTag: aa2a200bce0f2a2d9f4c15bda1eaa725396f59e4
- name: PROJECT_CLIENT
  newName: sirpacoder/client
  newTag: aa2a200bce0f2a2d9f4c15bda1eaa725396f59e4
- name: PROJECT_CRONJOB
  newName: sirpacoder/wiki_url
  newTag: aa2a200bce0f2a2d9f4c15bda1eaa725396f59e4
- name: PROJECT_SERVER
  newName: sirpacoder/server
  newTag: aa2a200bce0f2a2d9f4c15bda1eaa725396f59e4
