apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- broadcaster.yaml
- cronjob.yaml
- config-map.yaml
- ingress.yaml
- postgres-statefulset.yaml
- horizontalpodautoscaler.yaml

images:
- name: PROJECT_BROADCASTER
  newName: sirpacoder/broadcaster
  newTag: 81c762ca4274e4853eedf72c0482c74e4e9ccba2
- name: PROJECT_CRONJOB
  newName: sirpacoder/wiki_url
  newTag: 81c762ca4274e4853eedf72c0482c74e4e9ccba2

bases:
- ./client
- ./server

