apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- analysistemplate.yaml
- broadcaster.yaml
- client.yaml
- config-map.yaml
- cronjob.yaml
- server.yaml
- horizontalpodautoscaler.yaml
- ingress.yaml
- postgres-statefulset.yaml
- secret.enc.yaml
- server.yaml
images:
- name: PROJECT_BROADCASTER
  newName: sirpacoder/broadcaster
  newTag: a7aa83d9846a3b4c74d45bdf9209804c282e31a3
- name: PROJECT_CLIENT
  newName: sirpacoder/client
  newTag: a7aa83d9846a3b4c74d45bdf9209804c282e31a3
- name: PROJECT_CRONJOB
  newName: sirpacoder/wiki_url
  newTag: a7aa83d9846a3b4c74d45bdf9209804c282e31a3
- name: PROJECT_SERVER
  newName: sirpacoder/server
  newTag: a7aa83d9846a3b4c74d45bdf9209804c282e31a3
