apiVersion: v1
kind: Secret
metadata:
    name: postgres-pw
    namespace: project
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:B/QyzG4pV6/kQa7Ka5XBEcPNbhKGG7bCfHGb7MfChbz/2YRJpD+phtpdIHrN36I+2LO7QvtrWj3xDfoqiKunrh+8zpUE793OzRjOKoYKspS4c0mTopOrSsneJDvlJtltZpu5FEHDCT5QEp9mfitxArLR49RMPrg+MH+0,iv:uEOq2Fz2rIadNZX9u8IdSO2c9S2DSbaDLkZYMCAx93c=,tag:FchGcsjY5WgSwLxXwcZawA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16mzg7zg4dxzdwglaruq8k9chctxmq0w3kgskxel2036ug4s6m98qw0sa3e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcWVXU2VuRDRMRWdFVlQx
            THBzNUpQK3EzUk90Mk5BSkRIOGU3N1VGWDNRCkc4UFlmUTk4U056YkNhYklLTkZt
            N1dxWEdmMWpDSlhxcEVHTTJhU0JjVkEKLS0tIEZjOUp1V3p1Y212QlJBdkxWOFB2
            dTRvbzU1c04wTGtCSE9IdWtmb0dRZHMKP+bF+VkrK+y3VOddWV3W+jJiujecql1i
            RAAFul5AWDNNyuK3/KYYpMU9X2MhJkCqXnuLQ6HL3PPhbNq8DdWESg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-08T14:00:59Z"
    mac: ENC[AES256_GCM,data:PRspw0oLr/N0HuGNARJF4a96B/iXOpUXBVsVMkQ7Sh3TWIGFi6lUG+TRcKFO50sjqgxylNeUpcnzpIpZywoPIKahMHIJS4XnSiPdDcI5L95V4o7wDJEBfOs/iqDrN/VuySunEMap1MphuGzDB2vi+veXoyVQR5vft23pDEhbjew=,iv:m93mcrDbrKiD2/KMpQA2i+FWETxRNhrtCey0MTJDXos=,tag:DTVZJcaAMa8KuaHVGe6ACw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
