apiVersion: v1
kind: Secret
metadata:
    name: postgres-pw
    namespace: project
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:QC4XnFPEU3VHTAG9,iv:b/6xK9A7ZoRnaIXKmGKTckUmmVx5U/EFArKN4fpfWHw=,tag:/0CWb5piYtSkOkQ0pjj1WA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1helqcqsh9464r8chnwc2fzj8uv7vr5ntnsft0tn45v2xtz0hpfwq98cmsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRCtxM2FMcDdaNSs2Zkg2
            NmdWenBudW5vSDVlcStXdkltSGpDRGdsREJvCm9wNWN2L0lpbGVMS2dIZnhUYjVV
            elNaQS9iVjVIUG9BR3VIZkJEWUl0eEkKLS0tIGk2VGwrNXFSZ2tLY0pYclBldnJq
            aGt6TzNtSzdDVktvWUMxTUE3bGIrY1UKxOqJLPua3hleWZSVMLbBLtMRfx5px9aV
            FIJLaxM6wBfCHl+Nq17xM7k9Y6v+hvAKwFi/zg8GSM9P/LM14Kb0hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-08T13:56:47Z"
    mac: ENC[AES256_GCM,data:0P/ax8D1TR0ikcvcy2hROwu0U6T8fIhy+nVElXIM34GFIF4uxLB8OQnKuBOWeHLmvZevw24hLRHAfOrfVCXitkD9Azqi03GED69jQ1FJygb/moglXv4mgnBt68nJLeHwp1dxkMXtKxBbG5R5Jf8gBz9KVfFX/QXtyZIfSLmHA3o=,iv:9KtxKJvS9FmyyP1eUgfpYzGr9FhI/ibQDy/krIKAnqQ=,tag:DUFcmdIHIMOqB/n/RusIvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
