apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: PROJECT_CLIENT
          imagePullPolicy: Always
          resources:
            requests:
              memory: '1Gi'
              cpu: '500m'
            limits:
              memory: '10Gi'
              cpu: '500m'

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: client-svc
  namespace: project
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
